spaceship:
    token: ENC[AES256_GCM,data:uT0dbblw7ttdwSqbzapRLMUjm5oMaDZW7FbO6sE9aK21vBtNH+9gnsJyzyBxmvFxf+Lb/sE7Yj/LRmelc97Evw==,iv:NChrtkFHwO8fQled9D/ErqAxpetwPPo69h+32Ko/Q3w=,tag:Z99o9HmFRvCEx8KhxIBenQ==,type:str]
sops:
    age:
        - recipient: age1qssg5g2jkt9n68lq4hyjmr56uucnanckkvseecyanzflmyalpu3s2ss4g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSamlwWU9FWWhwV013Z3lu
            ZmVzaXVGMkNXRCtjNnRhZUE1cTYzcWJTZURvClRtSEtXa2hmQzlpMmh2cHBuMUhI
            YnE1bE5qL3U0NWdBYTRoYTAyOFBhUFkKLS0tIHZTV29JN0N6NFdGSWk4akovSlNN
            S0xpRy8zODIyS1VTeDRSTkxPeEoyN3MKoApbMaU784fpD3WluGNY/hQCEjdIzXMk
            EilsFIkEEdabFyUrm1MOSFE0+3AvasGhN8YOPY0UmFFL0W2pZwpW7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kq8slysaa6pndupg3z4gkypt9ul94lmdpg2q5ky28swms6jhuakq2qfjfy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPblcwSDk5UWljVENXdjJM
            S3k5bkh0L1FGM2NWYWVuV1ZpaDkwSFhnMlh3CjRGTDVZeXp3ei82UzNBcW9rb2N2
            ejIzcWNMOWJ2dWMveUZnMjJ1WkNXdGsKLS0tIHg3OGR0bytOYWRGeXhZQVRzMTVO
            RmpkTzFpUVBiMlRuMW1MNFhiSlBKTzQKYc2MiQrphgOXB0OMAjpQU9bofvetsR8d
            EVfxdCm5/bP4WKDvywQZGmAEDQPH/LDLOawXmxHODMex3RPxLdUKVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:32:37Z"
    mac: ENC[AES256_GCM,data:kwBQ96ErD+uFLh0wieMYiMtbZuv20YHtQE22kvbKJy6cmC5N1JqGFfiNR2BBxkO7exTLDEkr+LItA1eSG0ChqUx7tP/XdJdIF8UYTlD5wH/HyffUNOd45QJn/pk30ZJKVmj9FKj+Apkz+Ws9KT549dJ9Odoj6WaMG7nzcFw4wrI=,iv:frmriuckw38R3P2m68BTN/loSqXkwn5KlS5uyoHZOW4=,tag:W+qoZGC4jJeJcjlJcVdHWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
