spaceship:
    token: ENC[AES256_GCM,data:uT0dbblw7ttdwSqbzapRLMUjm5oMaDZW7FbO6sE9aK21vBtNH+9gnsJyzyBxmvFxf+Lb/sE7Yj/LRmelc97Evw==,iv:NChrtkFHwO8fQled9D/ErqAxpetwPPo69h+32Ko/Q3w=,tag:Z99o9HmFRvCEx8KhxIBenQ==,type:str]
sops:
    age:
        - recipient: age1qssg5g2jkt9n68lq4hyjmr56uucnanckkvseecyanzflmyalpu3s2ss4g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUHJkU0Npb2VQRGN3WlZJ
            RGQ0N3FqUDFVV0NCWHVmWlk1NW9uVHVIeHdZCnJUOE4yVHJENFYyZ1QwUTF1ekc0
            R2pIelcrRUU4ZHI4WGh1NkhjWXE2K1EKLS0tIGJmenZtQUZoOGM3ZXZJSGdLWFRt
            RGpqNWRCSElZWU43dVo2aHVKdmtmcFkKvcVgdHBbI9jTc07P6d9b3cS5WPuJc4IH
            RJavcqvAID/2Q2m6d5VEwWnCTQLc2WV6/sKEvxzxXEPobc8cpxUb8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19ylye887ugc583pectr3exg85fxwcss3v5yeu0y688hj6737gc8q3q5lad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYnRMUFYrQ0VaQWpyR3pk
            d3diaTVHR01UaDhKT1VWN3J4UmNCVEdhZmdrClArNXpCeWtST3hCUHdlTkpEdzdj
            MDl1QmFrYWFBcjlJMS9TQjZTNEFQRFkKLS0tIExjWG9BUThtdklYTTZtNUszZnI0
            aUtTK3RMSm5GbGNsdllESDBGNlJsUm8KFUkKS3CHScTcfC2cF98j2DZEgYTB9IGn
            SOyUrQVN/j4JxIp0HEkp9/zEJUq5OChFpmYJ3M8AxQ8n8UiMRQ4RAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T23:32:37Z"
    mac: ENC[AES256_GCM,data:kwBQ96ErD+uFLh0wieMYiMtbZuv20YHtQE22kvbKJy6cmC5N1JqGFfiNR2BBxkO7exTLDEkr+LItA1eSG0ChqUx7tP/XdJdIF8UYTlD5wH/HyffUNOd45QJn/pk30ZJKVmj9FKj+Apkz+Ws9KT549dJ9Odoj6WaMG7nzcFw4wrI=,iv:frmriuckw38R3P2m68BTN/loSqXkwn5KlS5uyoHZOW4=,tag:W+qoZGC4jJeJcjlJcVdHWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
