keys:
  - &admin_waynevanson age1qssg5g2jkt9n68lq4hyjmr56uucnanckkvseecyanzflmyalpu3s2ss4g9
  - &server_homelab age19ylye887ugc583pectr3exg85fxwcss3v5yeu0y688hj6737gc8q3q5lad
creation_rules:
  - path_regexp: ^.sops.secrets.yaml$
    key_groups:
      - age:
          - *admin_waynevanson
          - *server_homelab
