spaceship:
    client-id: ENC[AES256_GCM,data:RND0/RHPY1hx2AcmGLuNPgh0sxY=,iv:vk8BSFSFp8ASLGPXgUnjzBErfyUWxLACOB5I9iet/AA=,tag:pe+lOCG2qLSq/GdU4Q8cgg==,type:str]
    client-secret: ENC[AES256_GCM,data:WxtcJXEoJZADq5NdXNkh3fxD0SPRIjrgct7a6/Cjk16TQf4VbUd1UqPpNtnfhHNHnxwYU26qFSSdb4I9xQT1Qw==,iv:Y2OuX78lTKrfGQkqOLaLnMWp6jmKpnxEfHOpl7ng6Lk=,tag:gGgYT+wZAjAwWdgj2y1Bog==,type:str]
sops:
    age:
        - recipient: age1qssg5g2jkt9n68lq4hyjmr56uucnanckkvseecyanzflmyalpu3s2ss4g9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXanVWMExNaTczSTZKSWQz
            QzIxa0lFNmxwZXJXZUJUZTUySHR4M1h3NGxjCi82ZDZ2eEJxTlRpZzUyL29Sajds
            dUNvT2haaGZ3QkZEUHliS0ZoYzEreGsKLS0tIDVnTi9oM1BkN1NaR1NaRDBqWG85
            Zkx5OTJ0TW0wdnU4dUVmM2lxMTlqNVkKfLBmlwkGa7dR1VI2/i6jBi5yVRGfnna4
            dnne5vV+fX3vAcGLgi1YftrnHs7hFT+932dj13G4vnVKsJVxxK0wkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kq8slysaa6pndupg3z4gkypt9ul94lmdpg2q5ky28swms6jhuakq2qfjfy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMFFNaWcrSVRqOUEyd2Q3
            SDkzSFU2cHhxQzRiLzYyVE9oc1lUUm1MUmprCmNRSElQdnIrWjZaYzZKQ3ZXVGRu
            bmkzUWpNdS9ScGxOSjRCUXFNZVoxdTAKLS0tIEZOM2ZyOEZtdm01NFBRNlFrSTNi
            YmZTdUgxM3plMXVMdDZSb3hRWjRkVlkK1qnFgkBjzY/r44BTyaIol8BskbC+rtws
            SaiDFNwFJBy1FKKQBdKahMlIhSiK07ylXpHsPzqZ2Gck2cmwTxG2rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T07:57:34Z"
    mac: ENC[AES256_GCM,data:1juSYnrILA616dnd1FkDaXAbeEYlLbwIYL8gtQQhwihvthmqA4cQAQfvFjV8LWaopxv/g55Z+QSE2dEeVscF0VO5tgVfE0p6f/CTjtqDtxpmMvGcBMn6QmjC1QAfog3n9xqOWjyx4zGvQMD8gl1yVWUlXiiIxPh/N+GB28yCvZ4=,iv:FZz1RXrhKxUOy0EXzPJYNFzTmRMHx3tZiGi9jrlEVvw=,tag:l/gfy9KqXcr+R5fpB+g2FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
